"""genesis schema

Revision ID: a1a27441d35c
Revises:
Create Date: 2026-07-15 05:36:13.404121

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'a1a27441d35c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PROCEED', 'PARK', 'DECLINE', name='recommendation').create(op.get_bind())
    sa.Enum('ZOOM', 'TEAMS', 'IN_PERSON', 'PHONE', 'OTHER', name='meetingplatform').create(op.get_bind())
    sa.Enum('CRC_BID', 'RDTI', 'PHILANTHROPIC', 'GOVERNMENT_GRANT', 'PRIVATE', 'OTHER', name='fundingpathway').create(op.get_bind())
    sa.Enum('RECEIVED', 'INITIAL_SCREEN', 'DISCOVERY_MEETING', 'DEEP_ASSESSMENT', 'DUE_DILIGENCE', 'DECISION_PENDING', 'ACTIVE_SUPPORT', 'PARKED', 'DECLINED', 'COMPLETED', name='pipelinestage').create(op.get_bind())
    sa.Enum('REFERRAL', 'WEBSITE', 'EVENT', 'COLD_OUTREACH', 'INTERNAL', name='pitchsource').create(op.get_bind())
    sa.Enum('STARTUP', 'UNIVERSITY', 'NGO', 'GOVERNMENT', 'CONSORTIUM', 'RESEARCH_CENTRE', 'OTHER', name='orgtype').create(op.get_bind())
    sa.Enum('ADMIN', 'ASSESSOR', 'VIEWER', name='userrole').create(op.get_bind())
    op.create_table('organisations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('org_type', postgresql.ENUM('STARTUP', 'UNIVERSITY', 'NGO', 'GOVERNMENT', 'CONSORTIUM', 'RESEARCH_CENTRE', 'OTHER', name='orgtype', create_type=False), nullable=True),
    sa.Column('sector', sa.String(length=255), nullable=True),
    sa.Column('state_territory', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('abn', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organisations_name'), 'organisations', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('azure_oid', sa.String(length=255), nullable=True),
    sa.Column('role', postgresql.ENUM('ADMIN', 'ASSESSOR', 'VIEWER', name='userrole', create_type=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('azure_oid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('linkedin', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_contacted', sa.Date(), nullable=True),
    sa.Column('organisation_id', sa.Uuid(), nullable=True),
    sa.Column('relationship_owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['relationship_owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_name'), 'contacts', ['name'], unique=False)
    op.create_table('pitches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('submission_date', sa.Date(), nullable=True),
    sa.Column('source', postgresql.ENUM('REFERRAL', 'WEBSITE', 'EVENT', 'COLD_OUTREACH', 'INTERNAL', name='pitchsource', create_type=False), nullable=True),
    sa.Column('current_stage', postgresql.ENUM('RECEIVED', 'INITIAL_SCREEN', 'DISCOVERY_MEETING', 'DEEP_ASSESSMENT', 'DUE_DILIGENCE', 'DECISION_PENDING', 'ACTIVE_SUPPORT', 'PARKED', 'DECLINED', 'COMPLETED', name='pipelinestage', create_type=False), nullable=False),
    sa.Column('domain_tags', sa.Text(), nullable=True),
    sa.Column('funding_pathway', postgresql.ENUM('CRC_BID', 'RDTI', 'PHILANTHROPIC', 'GOVERNMENT_GRANT', 'PRIVATE', 'OTHER', name='fundingpathway', create_type=False), nullable=True),
    sa.Column('masterplan_alignment', sa.Text(), nullable=True),
    sa.Column('is_confidential', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=True),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pitches_title'), 'pitches', ['title'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('national_impact', sa.Integer(), nullable=False),
    sa.Column('translation_readiness', sa.Integer(), nullable=False),
    sa.Column('team_capability', sa.Integer(), nullable=False),
    sa.Column('ecosystem_fit', sa.Integer(), nullable=False),
    sa.Column('funding_pathway_clarity', sa.Integer(), nullable=False),
    sa.Column('masterplan_alignment', sa.Integer(), nullable=False),
    sa.Column('recommendation', postgresql.ENUM('PROCEED', 'PARK', 'DECLINE', name='recommendation', create_type=False), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('assessment_date', sa.Date(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('pitch_id', sa.Uuid(), nullable=False),
    sa.Column('assessor_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meetings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('meeting_time', sa.Time(), nullable=True),
    sa.Column('platform', postgresql.ENUM('ZOOM', 'TEAMS', 'IN_PERSON', 'PHONE', 'OTHER', name='meetingplatform', create_type=False), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_points', sa.Text(), nullable=True),
    sa.Column('action_items', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('recording_link', sa.String(length=1000), nullable=True),
    sa.Column('transcript_path', sa.String(length=1000), nullable=True),
    sa.Column('ai_import_status', sa.String(length=50), nullable=True),
    sa.Column('pitch_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pitch_contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pitch_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('role_in_pitch', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pitch_file_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pitch_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pitch_stage_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pitch_id', sa.Uuid(), nullable=False),
    sa.Column('from_stage', postgresql.ENUM('RECEIVED', 'INITIAL_SCREEN', 'DISCOVERY_MEETING', 'DEEP_ASSESSMENT', 'DUE_DILIGENCE', 'DECISION_PENDING', 'ACTIVE_SUPPORT', 'PARKED', 'DECLINED', 'COMPLETED', name='pipelinestage', create_type=False), nullable=True),
    sa.Column('to_stage', postgresql.ENUM('RECEIVED', 'INITIAL_SCREEN', 'DISCOVERY_MEETING', 'DEEP_ASSESSMENT', 'DUE_DILIGENCE', 'DECISION_PENDING', 'ACTIVE_SUPPORT', 'PARKED', 'DECLINED', 'COMPLETED', name='pipelinestage', create_type=False), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changed_by_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_attendees',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_attendees')
    op.drop_table('pitch_stage_history')
    op.drop_table('pitch_file_links')
    op.drop_table('pitch_contacts')
    op.drop_table('meetings')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_pitches_title'), table_name='pitches')
    op.drop_table('pitches')
    op.drop_index(op.f('ix_contacts_name'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organisations_name'), table_name='organisations')
    op.drop_table('organisations')
    sa.Enum('ADMIN', 'ASSESSOR', 'VIEWER', name='userrole').drop(op.get_bind())
    sa.Enum('STARTUP', 'UNIVERSITY', 'NGO', 'GOVERNMENT', 'CONSORTIUM', 'RESEARCH_CENTRE', 'OTHER', name='orgtype').drop(op.get_bind())
    sa.Enum('REFERRAL', 'WEBSITE', 'EVENT', 'COLD_OUTREACH', 'INTERNAL', name='pitchsource').drop(op.get_bind())
    sa.Enum('RECEIVED', 'INITIAL_SCREEN', 'DISCOVERY_MEETING', 'DEEP_ASSESSMENT', 'DUE_DILIGENCE', 'DECISION_PENDING', 'ACTIVE_SUPPORT', 'PARKED', 'DECLINED', 'COMPLETED', name='pipelinestage').drop(op.get_bind())
    sa.Enum('CRC_BID', 'RDTI', 'PHILANTHROPIC', 'GOVERNMENT_GRANT', 'PRIVATE', 'OTHER', name='fundingpathway').drop(op.get_bind())
    sa.Enum('ZOOM', 'TEAMS', 'IN_PERSON', 'PHONE', 'OTHER', name='meetingplatform').drop(op.get_bind())
    sa.Enum('PROCEED', 'PARK', 'DECLINE', name='recommendation').drop(op.get_bind())
    # ### end Alembic commands ###
