"""make (pitch_id, contact_id) unique in pitch_contacts

Revision ID: a3d7e5c81b40
Revises: c8d1f0a45e29
Create Date: 2026-08-20 00:00:00.000000

A person is on a pitch or is not; there is no meaning to being on it twice. Two
rows for one pair would double that person's name and inflate the count
everywhere `contact_ids` is read, since it is a plain list comprehension over the
join rows.

Nothing enforced this before. Uniqueness held only as a side effect of every
write replacing the whole set (`_set_contacts` collapses its input with
`dict.fromkeys`), which is not a guarantee a second writer or a future per-link
attach endpoint would respect.

Hand-written rather than autogenerated: `sop/db-change.md` §3 warns that
autogenerate is unreliable or silent on constraints.

**Touches data.** A unique index cannot be built over existing duplicates, so any
are collapsed first, keeping the lowest `id` per pair so the result is
deterministic and a re-applied `upgrade()` is stable. Check what this will remove
before applying:

    SELECT pitch_id, contact_id, count(*) FROM pitch_contacts
    GROUP BY 1, 2 HAVING count(*) > 1;

`downgrade()` drops the constraint but cannot bring the collapsed rows back. That
loses nothing meaningful — they were redundant by definition — but it does mean
the round trip is not byte-for-byte.
"""
from collections.abc import Sequence

from alembic import op

revision: str = 'a3d7e5c81b40'
down_revision: str | None = 'c8d1f0a45e29'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ROW_NUMBER rather than MIN(id): Postgres has no MIN aggregate for uuid.
    op.execute(
        """
        DELETE FROM pitch_contacts
         WHERE id IN (
               SELECT id
                 FROM (
                       SELECT id,
                              ROW_NUMBER() OVER (
                                  PARTITION BY pitch_id, contact_id ORDER BY id
                              ) AS row_number
                         FROM pitch_contacts
                      ) ranked
                WHERE row_number > 1
         )
        """
    )

    op.create_unique_constraint(
        'uq_pitch_contacts_pair', 'pitch_contacts', ['pitch_id', 'contact_id']
    )


def downgrade() -> None:
    op.drop_constraint('uq_pitch_contacts_pair', 'pitch_contacts', type_='unique')
